services:
  # ProverbSeed: Sert les fichiers compilés (dist) par Nginx
  proverbseed:
    build: .
    container_name: proverbseed
    volumes:
      # On garde uniquement la config Nginx si on veut pouvoir la modifier sans rebuild, 
      # mais elle est déjà copiée dans le Dockerfile. On peut la laisser pour le dev.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.proverbseed.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.proverbseed.tls=true
      - traefik.http.routers.proverbseed.entrypoints=websecure
      - traefik.http.routers.proverbseed.tls.certresolver=letsencrypt
      - traefik.http.middlewares.proverbseed.headers.SSLRedirect=true
      - traefik.http.middlewares.proverbseed.headers.STSSeconds=315360000
      - traefik.http.middlewares.proverbseed.headers.browserXSSFilter=true
      - traefik.http.middlewares.proverbseed.headers.contentTypeNosniff=true
      - traefik.http.middlewares.proverbseed.headers.forceSTSHeader=true
      - traefik.http.middlewares.proverbseed.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.proverbseed.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.proverbseed.headers.STSPreload=true
      - traefik.http.routers.proverbseed.middlewares=proverbseed@docker
      - traefik.http.services.proverbseed.loadbalancer.server.port=80

networks:
  proxy:
    external: true
