#!/usr/bin/env python3
"""
Generate proverbs_en.json using World English Bible (WEB) text.
The WEB is public domain (https://worldenglish.bible).
Structure mirrors proverbs_fr.json exactly (same IDs, same unit groupings).
"""
import json

# ─────────────────────────────────────────────────────────────────────────────
# World English Bible (WEB) — Proverbs 10–29 (public domain)
# ─────────────────────────────────────────────────────────────────────────────

WEB = {}

WEB[10] = {
    1:  "The proverbs of Solomon. A wise son makes a glad father, but a foolish son brings grief to his mother.",
    2:  "Ill-gotten treasures bring no profit, but righteousness delivers from death.",
    3:  "Yahweh will not allow the soul of the righteous to go hungry, but he thwarts the craving of the wicked.",
    4:  "A slack hand causes poverty, but the hand of the diligent brings wealth.",
    5:  "He who gathers in summer is a wise son, but he who sleeps during harvest is a son who causes shame.",
    6:  "Blessings are on the head of the righteous, but violence covers the mouth of the wicked.",
    7:  "The memory of the righteous is blessed, but the name of the wicked will rot.",
    8:  "The wise in heart will receive commandments, but a babbling fool will be thrown down.",
    9:  "He who walks blamelessly walks surely, but he who perverts his ways will be found out.",
    10: "One who winks the eye causes sorrow, and a babbling fool will be thrown down.",
    11: "The mouth of the righteous is a spring of life, but violence covers the mouth of the wicked.",
    12: "Hatred stirs up strife, but love covers all wrongs.",
    13: "Wisdom is found on the lips of the discerning, but a rod is for the back of one who lacks understanding.",
    14: "Wise men store up knowledge, but the mouth of the foolish is near ruin.",
    15: "The rich man's wealth is his strong city. The destruction of the poor is their poverty.",
    16: "The labor of the righteous leads to life. The increase of the wicked leads to sin.",
    17: "He is in the way of life who heeds correction, but he who forsakes reproof leads others astray.",
    18: "He who conceals hatred has lying lips. He who utters a slander is a fool.",
    19: "In the multitude of words there is no lack of sin, but he who restrains his lips does wisely.",
    20: "The tongue of the righteous is like choice silver. The heart of the wicked is of little worth.",
    21: "The lips of the righteous feed many, but the foolish die for lack of understanding.",
    22: "Yahweh's blessing brings wealth, and he adds no trouble to it.",
    23: "It is like sport to a fool to do wickedness, but wisdom is a pleasure to a man of understanding.",
    24: "What the wicked fears will overtake him, but the desire of the righteous will be granted.",
    25: "When the whirlwind passes, the wicked is no more; but the righteous is an everlasting foundation.",
    26: "As vinegar to the teeth, and as smoke to the eyes, so is the sluggard to those who send him.",
    27: "The fear of Yahweh prolongs days, but the years of the wicked shall be shortened.",
    28: "The prospect of the righteous is joy, but the hope of the wicked will perish.",
    29: "The way of Yahweh is a stronghold to the upright, but it is a destruction to the workers of iniquity.",
    30: "The righteous will never be removed, but the wicked will not dwell in the land.",
    31: "The mouth of the righteous produces wisdom, but the perverse tongue will be cut off.",
    32: "The lips of the righteous know what is acceptable, but the mouth of the wicked is perverse.",
}

WEB[11] = {
    1:  "A false balance is an abomination to Yahweh, but accurate weights are his delight.",
    2:  "When pride comes, then comes shame, but with the lowly is wisdom.",
    3:  "The integrity of the upright guides them, but the perverseness of the treacherous destroys them.",
    4:  "Riches don't profit in the day of wrath, but righteousness delivers from death.",
    5:  "The righteousness of the blameless will direct his way, but the wicked will fall by his own wickedness.",
    6:  "The righteousness of the upright will deliver them, but the unfaithful will be trapped by evil desires.",
    7:  "When a wicked man dies, hope perishes, and expectation of power comes to nothing.",
    8:  "A righteous person is delivered out of trouble, and the wicked takes his place.",
    9:  "With his mouth the godless man destroys his neighbor, but through knowledge the righteous are rescued.",
    10: "When it goes well with the righteous, the city rejoices. When the wicked perish, there is shouting.",
    11: "By the blessing of the upright, the city is exalted, but it is overthrown by the mouth of the wicked.",
    12: "One who despises his neighbor is void of wisdom, but a man of understanding holds his peace.",
    13: "One who brings gossip betrays a confidence, but one who is of a trustworthy spirit is one who keeps a secret.",
    14: "Where there is no wise guidance, the nation falls, but in the multitude of counselors there is victory.",
    15: "He who is collateral for a stranger will suffer for it, but he who refuses pledges is secure.",
    16: "A gracious woman obtains honor, but violent men obtain riches.",
    17: "The merciful man does good to his own soul, but he who is cruel troubles his own flesh.",
    18: "Wicked people earn deceitful wages, but one who sows righteousness reaps a sure reward.",
    19: "He who is truly righteous gets life. He who pursues evil gets death.",
    20: "Those who are perverse in heart are an abomination to Yahweh, but those whose ways are blameless are his delight.",
    21: "Most certainly, the evil man will not go unpunished, but the offspring of the righteous will be delivered.",
    22: "Like a gold ring in a pig's snout is a beautiful woman who lacks discretion.",
    23: "The desire of the righteous is only good. The expectation of the wicked is wrath.",
    24: "There is one who scatters, and yet increases; there is one who withholds more than is appropriate, but gains poverty.",
    25: "The generous soul will be made rich. He who waters will be watered also himself.",
    26: "People curse one who withholds grain, but blessing will be on the head of one who sells it.",
    27: "He who diligently seeks good seeks favor, but he who searches after evil, it shall come to him.",
    28: "He who trusts in his riches will fall, but the righteous shall flourish as the green leaf.",
    29: "He who troubles his own house will inherit the wind. The foolish will be servant to the wise of heart.",
    30: "The fruit of the righteous is a tree of life. He who is wise wins souls.",
    31: "Behold, the righteous shall be repaid in the earth; how much more the wicked and the sinner!",
}

WEB[12] = {
    1:  "Whoever loves correction loves knowledge, but he who hates reproof is stupid.",
    2:  "A good man shall obtain favor from Yahweh, but he will condemn a man of wicked devices.",
    3:  "A man shall not be established by wickedness, but the root of the righteous shall not be moved.",
    4:  "A worthy wife is the crown of her husband, but a disgraceful wife is as rottenness in his bones.",
    5:  "The thoughts of the righteous are just, but the advice of the wicked is deceitful.",
    6:  "The words of the wicked are a deadly ambush, but the speech of the upright rescues them.",
    7:  "The wicked are overthrown, and are no more, but the house of the righteous shall stand.",
    8:  "A man shall be commended according to his wisdom, but he who has a warped mind shall be despised.",
    9:  "Better is he who is lightly esteemed and has a servant, than he who honors himself and lacks bread.",
    10: "A righteous man respects the life of his animal, but the tender mercies of the wicked are cruel.",
    11: "One who tills his land will have plenty of bread, but one who chases fantasies is void of understanding.",
    12: "The wicked desires the prey of evil men, but the root of the righteous flourishes.",
    13: "An evil man is trapped by sinful talk, but a righteous man escapes from trouble.",
    14: "A man shall be satisfied with good by the fruit of his mouth. The work of a man's hands shall be rewarded.",
    15: "The way of a fool is right in his own eyes, but he who is wise listens to counsel.",
    16: "A fool shows his annoyance the same day, but a prudent man ignores an insult.",
    17: "An honest witness tells the truth, but a false witness tells lies.",
    18: "There is one who speaks rashly like the piercing of a sword, but the tongue of the wise heals.",
    19: "Truth's lips will be established forever, but a lying tongue is only momentary.",
    20: "Deceit is in the heart of those who plot evil, but joy comes to the promoters of peace.",
    21: "No mischief shall happen to the righteous, but the wicked shall be filled with evil.",
    22: "Lying lips are an abomination to Yahweh, but those who do the truth are his delight.",
    23: "A prudent man keeps his knowledge quiet, but the heart of fools proclaims foolishness.",
    24: "The hands of the diligent ones shall rule, but laziness ends in slave labor.",
    25: "Anxiety in a man's heart weighs it down, but a kind word makes it glad.",
    26: "A righteous person is cautious in friendship, but the way of the wicked leads them astray.",
    27: "The lazy man doesn't roast his game, but the possessions of diligent men are prized.",
    28: "In the path of righteousness is life, and the way of its path is toward immortality.",
}

WEB[13] = {
    1:  "A wise son listens to his father's instruction, but a scoffer doesn't listen to rebuke.",
    2:  "By the fruit of his lips, a man enjoys good things, but the unfaithful crave violence.",
    3:  "He who guards his mouth guards his soul. One who opens wide his lips comes to ruin.",
    4:  "The soul of the sluggard desires, and has nothing, but the desire of the diligent shall be fully satisfied.",
    5:  "A righteous man hates lying, but a wicked man brings shame and disgrace.",
    6:  "Righteousness guards the one whose way is blameless, but wickedness overthrows the sinner.",
    7:  "There are some who pretend to be rich, yet have nothing. There are some who pretend to be poor, yet have great wealth.",
    8:  "The ransom of a man's life is his riches, but the poor hear no threats.",
    9:  "The light of the righteous shines brightly, but the lamp of the wicked is snuffed out.",
    10: "Pride only breeds quarrels, but wisdom is with those who take advice.",
    11: "Wealth gained by dishonesty dwindles away, but he who gathers by hand makes it grow.",
    12: "Hope deferred makes the heart sick, but when longing is fulfilled, it is a tree of life.",
    13: "Whoever despises instruction will pay for it, but he who respects a commandment will be rewarded.",
    14: "The teaching of the wise is a spring of life, to turn from the snares of death.",
    15: "Good understanding wins favor, but the way of the unfaithful is hard.",
    16: "Every prudent man acts from knowledge, but a fool exposes folly.",
    17: "A wicked messenger falls into trouble, but a trustworthy envoy brings healing.",
    18: "Poverty and shame come to him who refuses discipline, but he who heeds correction shall be honored.",
    19: "Longing fulfilled is sweet to the soul, but fools detest turning from evil.",
    20: "One who walks with wise men grows wise, but a companion of fools suffers harm.",
    21: "Calamity pursues sinners, but prosperity shall reward the righteous.",
    22: "A good man leaves an inheritance to his children's children, but the wealth of the sinner is stored up for the righteous.",
    23: "An unplowed field of the poor yields much food, but injustice sweeps it away.",
    24: "One who spares the rod hates his son, but one who loves him is careful to discipline him.",
    25: "A righteous man eats until his soul is satisfied, but the belly of the wicked goes hungry.",
}

WEB[14] = {
    1:  "Every wise woman builds her house, but the foolish one tears it down with her own hands.",
    2:  "He who walks in his uprightness fears Yahweh, but he who is perverse in his ways despises him.",
    3:  "The fool's talk brings a rod to his back, but the lips of the wise protect them.",
    4:  "Where no oxen are, the crib is clean, but much increase comes by the strength of the ox.",
    5:  "A truthful witness will not lie, but a false witness breathes out lies.",
    6:  "A scoffer seeks wisdom and doesn't find it, but knowledge comes easily to a discerning person.",
    7:  "Stay away from a foolish man, for you won't find knowledge on his lips.",
    8:  "The wisdom of the prudent is to think about his way, but the folly of fools is deceit.",
    9:  "Fools mock at making amends for sin, but among the upright there is goodwill.",
    10: "The heart knows its own bitterness and joy; he will not share these with a stranger.",
    11: "The house of the wicked shall be overthrown, but the tent of the upright shall flourish.",
    12: "There is a way which seems right to a man, but in the end it leads to death.",
    13: "Even in laughter the heart may be sorrowful, and mirth may end in heaviness.",
    14: "The unfaithful will be fully repaid for his own ways. A good man shall be satisfied by his.",
    15: "A simple man believes everything, but the prudent man carefully considers his steps.",
    16: "A wise man fears, and shuns evil, but the fool is hot-headed and reckless.",
    17: "He who is quick to become angry will commit folly, and a crafty man is hated.",
    18: "The simple inherit folly, but the prudent are crowned with knowledge.",
    19: "The evil bow down before the good, and the wicked at the gates of the righteous.",
    20: "The poor person is shunned even by his own neighbor, but the rich man has many friends.",
    21: "He who despises his neighbor sins, but blessed is he who has pity on the poor.",
    22: "Don't those who plan evil go astray? But love and faithfulness belong to those who plan good.",
    23: "In all hard work there is profit, but the talk of the lips leads only to poverty.",
    24: "The crown of the wise is their riches, but the folly of fools crowns them with folly.",
    25: "A truthful witness saves lives, but a false witness is deceitful.",
    26: "In the fear of Yahweh is a secure fortress, and he will be a refuge for his children.",
    27: "The fear of Yahweh is a fountain of life, that one may escape deadly snares.",
    28: "In the multitude of people is the king's glory, but in the lack of people is the destruction of the prince.",
    29: "He who is slow to anger has great understanding, but he who has a quick temper displays folly.",
    30: "The life of the body is a heart at peace, but envy rots the bones.",
    31: "He who oppresses the poor shows contempt for his Maker, but he who is kind to the needy honors him.",
    32: "The wicked is brought down in his calamity, but in death, the righteous has a refuge.",
    33: "Wisdom rests in the heart of one who has understanding, and is even made known in the midst of fools.",
    34: "Righteousness exalts a nation, but sin is a disgrace to any people.",
    35: "The king's favor is toward a servant who deals wisely, but his wrath is toward one who acts shamefully.",
}

WEB[15] = {
    1:  "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    2:  "The tongue of the wise commends knowledge, but the mouth of the fool gushes out folly.",
    3:  "Yahweh's eyes are everywhere, keeping watch on the evil and the good.",
    4:  "A gentle tongue is a tree of life, but deceit in it crushes the spirit.",
    5:  "A fool despises his father's instruction, but he who heeds reproof shows prudence.",
    6:  "In the house of the righteous is much treasure, but the income of the wicked brings trouble.",
    7:  "The lips of the wise spread knowledge; not so the hearts of fools.",
    8:  "The sacrifice of the wicked is an abomination to Yahweh, but the prayer of the upright is his delight.",
    9:  "The way of the wicked is an abomination to Yahweh, but he loves him who follows after righteousness.",
    10: "There is stern discipline for one who forsakes the way: whoever hates reproof shall die.",
    11: "Sheol and Abaddon are before Yahweh— how much more then the hearts of the children of men!",
    12: "A scoffer doesn't love to be reproved; he will not go to the wise.",
    13: "A glad heart makes a cheerful face, but an aching heart breaks the spirit.",
    14: "The discerning heart seeks knowledge, but the mouth of fools feeds on folly.",
    15: "All the days of the afflicted are wretched, but one who has a cheerful heart has a continual feast.",
    16: "Better is little with the fear of Yahweh, than great treasure with trouble.",
    17: "Better is a meal of vegetables where love is, than a fattened calf with hatred.",
    18: "A wrathful man stirs up contention, but one who is slow to anger appeases strife.",
    19: "The way of the sluggard is like a thorn patch, but the path of the upright is a highway.",
    20: "A wise son makes a father glad, but a foolish man despises his mother.",
    21: "Folly is joy to one who is void of wisdom, but a man of understanding keeps his way straight.",
    22: "Where there is no counsel, plans fail; but in a multitude of counselors they are established.",
    23: "Joy comes to a man with the reply of his mouth. How good is a word at the right time!",
    24: "The path of life leads upward for the wise, that he may avoid Sheol below.",
    25: "Yahweh will uproot the house of the proud, but he will keep the widow's borders intact.",
    26: "Yahweh detests the thoughts of the wicked, but the thoughts of the pure are pleasing.",
    27: "He who is greedy for gain troubles his own house, but he who hates bribes will live.",
    28: "The heart of the righteous weighs answers, but the mouth of the wicked gushes out evil.",
    29: "Yahweh is far from the wicked, but he hears the prayer of the righteous.",
    30: "The light of the eyes rejoices the heart. Good news gives health to the bones.",
    31: "The ear that listens to life-giving reproof will dwell among the wise.",
    32: "He who refuses correction despises his own soul, but he who listens to reproof gets understanding.",
    33: "The fear of Yahweh teaches wisdom. Before honor is humility.",
}

WEB[16] = {
    1:  "The plans of the heart belong to man, but the answer of the tongue is from Yahweh.",
    2:  "All the ways of a man are clean in his own eyes, but Yahweh weighs the motives.",
    3:  "Commit your deeds to Yahweh, and your plans will succeed.",
    4:  "Yahweh has made everything for its own purpose, yes, even the wicked for the day of evil.",
    5:  "Everyone who is proud in heart is an abomination to Yahweh: they shall certainly not be unpunished.",
    6:  "By mercy and truth, iniquity is atoned for. By the fear of Yahweh, men depart from evil.",
    7:  "When a man's ways please Yahweh, he makes even his enemies to be at peace with him.",
    8:  "Better is a little with righteousness than great revenues with injustice.",
    9:  "A man's heart plans his course, but Yahweh directs his steps.",
    10: "Inspired judgments are on the lips of the king. He shall not betray his mouth.",
    11: "Honest balances and scales are Yahweh's; all the weights in the bag are his work.",
    12: "It is an abomination for kings to do wrong, for the throne is established by righteousness.",
    13: "Righteous lips are the delight of kings. They value one who speaks the truth.",
    14: "The king's wrath is a messenger of death, but a wise man will pacify it.",
    15: "In the light of the king's face is life. His favor is like a cloud of the spring rain.",
    16: "How much better it is to get wisdom than gold! Yes, to get understanding is to be chosen rather than silver.",
    17: "The highway of the upright is to depart from evil. He who keeps his way preserves his soul.",
    18: "Pride goes before destruction, and a haughty spirit before a fall.",
    19: "It is better to be of a humble spirit with the poor than to divide the plunder with the proud.",
    20: "He who heeds the Word finds prosperity. Whoever trusts in Yahweh is blessed.",
    21: "The wise in heart shall be called prudent. Pleasantness of the lips promotes instruction.",
    22: "Understanding is a fountain of life to one who has it, but the punishment of fools is their folly.",
    23: "The heart of the wise makes his speech judicious, and increases persuasiveness in his lips.",
    24: "Pleasant words are like a honeycomb: sweet to the soul, and health to the bones.",
    25: "There is a way that seems right to a man, but in the end it leads to death.",
    26: "The appetite of the laboring man labors for him; for his mouth urges him on.",
    27: "A worthless man devises mischief. His speech is like a scorching fire.",
    28: "A perverse man stirs up strife. A whisperer separates close friends.",
    29: "A man of violence entices his neighbor, and leads him in a way that is not good.",
    30: "One who winks his eyes to plot perversions, one who presses his lips together, has accomplished evil.",
    31: "Gray hair is a crown of glory. It is attained by a life of righteousness.",
    32: "One who is slow to anger is better than the mighty; one who rules his spirit, than he who takes a city.",
    33: "The lot is cast into the lap, but its every decision is from Yahweh.",
}

WEB[17] = {
    1:  "Better is a dry morsel with quietness, than a house full of feasting with strife.",
    2:  "A servant who deals wisely will rule over a son who acts shamefully, and shall share in the inheritance among brothers.",
    3:  "The refining pot is for silver, and the furnace for gold, but Yahweh tests the hearts.",
    4:  "An evildoer heeds wicked lips. A liar gives ear to a mischievous tongue.",
    5:  "Whoever mocks the poor reproaches his Maker. He who is glad at calamity shall not be unpunished.",
    6:  "Children's children are the crown of old men; the glory of children are their parents.",
    7:  "A lying tongue doesn't suit a noble; much less do lying lips a prince.",
    8:  "A bribe is like a precious stone in the eyes of him who gives it; wherever he turns, he prospers.",
    9:  "He who covers an offense promotes love; but he who repeats a matter separates close friends.",
    10: "A rebuke enters deeper into one who has understanding than a hundred lashes into a fool.",
    11: "An evil man seeks only rebellion; therefore a cruel messenger shall be sent against him.",
    12: "Let a bear robbed of her cubs meet a man, rather than a fool in his folly.",
    13: "Whoever rewards evil for good, evil shall not depart from his house.",
    14: "The beginning of strife is like breaching a dam, therefore stop contention before quarreling breaks out.",
    15: "He who justifies the wicked, and he who condemns the righteous, both of them alike are an abomination to Yahweh.",
    16: "Why is there money in the hand of a fool to buy wisdom, since he has no understanding?",
    17: "A friend loves at all times; and a brother is born for adversity.",
    18: "A man void of understanding pledges, and becomes collateral in the presence of his neighbor.",
    19: "He who loves disobedience loves strife. One who builds a high gate seeks destruction.",
    20: "One who has a crooked heart doesn't find prosperity, and one who has a perverse tongue falls into trouble.",
    21: "He who becomes the parent of a fool grieves. The father of a fool has no joy.",
    22: "A cheerful heart makes good medicine, but a crushed spirit dries up the bones.",
    23: "A wicked man receives a bribe in secret, to pervert the ways of justice.",
    24: "Wisdom is before the face of one who has understanding, but the eyes of a fool wander to the ends of the earth.",
    25: "A foolish son brings grief to his father, and bitterness to her who bore him.",
    26: "Also to punish the righteous is not good, nor to flog officials for their integrity.",
    27: "He who spares his words has knowledge. He who is even tempered is a man of understanding.",
    28: "Even a fool, when he keeps silent, is considered wise. When he shuts his lips, he is thought to be discerning.",
}

WEB[18] = {
    1:  "An unfriendly man pursues selfish ends, and against all sound judgment starts quarrels.",
    2:  "A fool takes no pleasure in understanding, but only in expressing his opinion.",
    3:  "When wickedness comes, contempt also comes, and with shame comes disgrace.",
    4:  "The words of a man's mouth are like deep waters. The fountain of wisdom is like a flowing brook.",
    5:  "It is not good to be partial to the wicked, or to deprive the innocent of justice.",
    6:  "A fool's lips come into contention, and his mouth invites beatings.",
    7:  "A fool's mouth is his destruction, and his lips are a snare to his soul.",
    8:  "The words of a gossip are like dainty morsels: they go down into a person's innermost parts.",
    9:  "One who is slack in his work is brother to him who is a master of destruction.",
    10: "The name of Yahweh is a strong tower: the righteous run to him, and are safe.",
    11: "The rich man's wealth is his strong city, like a high wall in his own imagination.",
    12: "Before destruction the heart of man is proud, but before honor is humility.",
    13: "He who gives answer before he hears, that is folly and shame to him.",
    14: "A man's spirit will sustain him in sickness, but a crushed spirit, who can bear?",
    15: "The heart of the discerning gets knowledge. The ear of the wise seeks knowledge.",
    16: "A man's gift makes room for him, and brings him before great men.",
    17: "He who pleads his cause first seems right; until his neighbor comes and examines him.",
    18: "The lot settles disputes, and keeps strong ones apart.",
    19: "A brother offended is more unyielding than a fortified city, and disputes are like the bars of a fortress.",
    20: "A man's belly shall be filled with the fruit of his mouth. With the harvest of his lips he shall be satisfied.",
    21: "Death and life are in the power of the tongue; those who love it will eat its fruit.",
    22: "Whoever finds a wife finds a good thing, and obtains favor of Yahweh.",
    23: "The poor man begs for mercy, but the rich man answers harshly.",
    24: "A man of many companions may be ruined, but there is a friend who sticks closer than a brother.",
}

WEB[19] = {
    1:  "Better is the poor who walks in his integrity than he who is perverse in his lips and is a fool.",
    2:  "It isn't good to have zeal without knowledge; nor being hasty with one's feet and missing the way.",
    3:  "The foolishness of man subverts his way; his heart rages against Yahweh.",
    4:  "Wealth adds many friends, but the poor is separated from his friend.",
    5:  "A false witness shall not be unpunished. He who pours out lies shall not go free.",
    6:  "Many will entreat the favor of a ruler, and everyone is a friend to a man who gives gifts.",
    7:  "All the relatives of the poor shun him; how much more do his friends go far from him! He pursues them with pleas, but they are gone.",
    8:  "Whoever gets wisdom loves his own soul. He who keeps understanding shall find good.",
    9:  "A false witness shall not be unpunished. He who breathes out lies shall perish.",
    10: "Luxury is not fitting for a fool; much less for a servant to have rule over princes.",
    11: "The discretion of a man makes him slow to anger. It is his glory to overlook an offense.",
    12: "The king's wrath is like the roaring of a lion, but his favor is like dew on the grass.",
    13: "A foolish son is the calamity of his father. A wife's quarrels are a continual dripping.",
    14: "House and riches are an inheritance from fathers, but a prudent wife is from Yahweh.",
    15: "Slothfulness casts into a deep sleep. The idle soul shall suffer hunger.",
    16: "He who keeps the commandment keeps his soul, but he who is contemptuous in his ways shall die.",
    17: "He who has pity on the poor lends to Yahweh; he will reward him.",
    18: "Discipline your son while there is hope, and don't set your heart on his destruction.",
    19: "A hot-tempered man must pay the penalty, for if you rescue him, you must do it again.",
    20: "Listen to counsel and receive instruction, that you may be wise in your latter end.",
    21: "There are many plans in a man's heart, but Yahweh's counsel will prevail.",
    22: "That which makes a man to be desired is his kindness. A poor man is better than a liar.",
    23: "The fear of Yahweh leads to life, then contentment; he rests and will not be visited by trouble.",
    24: "The sluggard buries his hand in the dish; he will not so much as bring it to his mouth again.",
    25: "Flog a scoffer, and the simple will learn prudence; rebuke one who has understanding, and he will gain knowledge.",
    26: "He who assaults his father and chases away his mother is a son who causes shame and brings reproach.",
    27: "If you stop listening to instruction, my son, you will stray from the words of knowledge.",
    28: "A corrupt witness mocks justice, and the mouth of the wicked gulps down iniquity.",
    29: "Penalties are prepared for scoffers, and beatings for the backs of fools.",
}

WEB[20] = {
    1:  "Wine is a mocker and beer is a brawler. Whoever is led astray by them is not wise.",
    2:  "The terror of a king is like the roaring of a lion. He who provokes him to anger sins against his own life.",
    3:  "It is an honor for a man to keep aloof from strife; but every fool will be quarreling.",
    4:  "The sluggard will not plow by reason of the autumn; therefore he shall beg in harvest, and have nothing.",
    5:  "Counsel in the heart of man is like deep water; but a man of understanding will draw it out.",
    6:  "Most men will proclaim each his own kindness, but who can find a faithful man?",
    7:  "A righteous man walks in integrity. Blessed are his children after him.",
    8:  "A king who sits on the throne of judgment scatters away all evil with his eyes.",
    9:  "Who can say, 'I have made my heart pure. I am clean and without sin'?",
    10: "Differing weights and differing measures, both of them alike are an abomination to Yahweh.",
    11: "Even a child makes himself known by his doings, whether his work is pure, and whether it is right.",
    12: "The hearing ear, and the seeing eye, Yahweh has made even both of them.",
    13: "Don't love sleep, lest you come to poverty. Open your eyes, and you shall be satisfied with bread.",
    14: "'It's no good, it's no good,' says the buyer; but when he is gone his way, then he boasts.",
    15: "There is gold and abundance of rubies; but the lips of knowledge are a rare jewel.",
    16: "Take the garment of one who puts up collateral for a stranger; and hold him in pledge for a wayward woman.",
    17: "Fraudulent food is sweet to a man, but afterwards his mouth is filled with gravel.",
    18: "Plans are established by counsel; by wise guidance you wage war.",
    19: "One who goes about as a tale-bearer reveals secrets; therefore don't keep company with one who opens wide his lips.",
    20: "Whoever curses his father or his mother, his lamp shall be put out in blackness of darkness.",
    21: "An inheritance quickly gained at the beginning won't be blessed in the end.",
    22: "Don't say, 'I will pay back evil.' Wait for Yahweh, and he will save you.",
    23: "Yahweh detests differing weights, and dishonest scales are not pleasing.",
    24: "A man's steps are from Yahweh; how then can man understand his way?",
    25: "It is a snare to a man to make a rash dedication, then later to reconsider his vows.",
    26: "A wise king winnows out the wicked, and drives the threshing wheel over them.",
    27: "The spirit of man is Yahweh's lamp, searching all his innermost parts.",
    28: "Love and faithfulness keep the king safe. His throne is sustained by love.",
    29: "The glory of young men is their strength. The dignity of old men is their gray hair.",
    30: "Wounding blows cleanse away evil, and beatings purge the innermost parts.",
}

WEB[21] = {
    1:  "The king's heart is in Yahweh's hand like the watercourses. He turns it wherever he desires.",
    2:  "Every way of a man is right in his own eyes, but Yahweh weighs the hearts.",
    3:  "To do righteousness and justice is more acceptable to Yahweh than sacrifice.",
    4:  "A high look, and a proud heart, the lamp of the wicked, is sin.",
    5:  "The plans of the diligent lead surely to profit; but everyone who is hasty comes surely to poverty.",
    6:  "Getting treasures by a lying tongue is a fleeting vapor for those who seek death.",
    7:  "The violence of the wicked will drive them away, because they refuse to do what is right.",
    8:  "The way of the guilty is devious, but the conduct of the innocent is upright.",
    9:  "It is better to dwell in the corner of a housetop than to share a house with a contentious woman.",
    10: "The soul of the wicked desires evil; his neighbor finds no mercy in his eyes.",
    11: "When the mocker is punished, the simple gains wisdom. When the wise is instructed, he receives knowledge.",
    12: "The righteous man considers the house of the wicked, and brings the wicked to ruin.",
    13: "Whoever stops his ears at the cry of the poor, he will also cry out and will not be heard.",
    14: "A gift in secret pacifies anger; and a bribe in the cloak, strong wrath.",
    15: "It is joy to the righteous to do justice, but it is a destruction to the workers of iniquity.",
    16: "The man who wanders out of the way of understanding shall rest in the assembly of the departed spirits.",
    17: "He who loves pleasure shall be a poor man. He who loves wine and oil shall not be rich.",
    18: "The wicked is a ransom for the righteous; the treacherous in the place of the upright.",
    19: "It is better to dwell in a desert land, than with a contentious and fretful woman.",
    20: "There is precious treasure and oil in the dwelling of the wise, but a foolish man swallows it up.",
    21: "He who follows after righteousness and kindness finds life, righteousness, and honor.",
    22: "A wise man scales the city of the mighty, and brings down the strength of its confidence.",
    23: "Whoever guards his mouth and his tongue keeps his soul from troubles.",
    24: "The proud and arrogant man, 'Mocker' is his name; he works in the arrogance of pride.",
    25: "The desire of the sluggard kills him, for his hands refuse to labor.",
    26: "There are those who covet greedily all day long; but the righteous give and don't withhold.",
    27: "The sacrifice of the wicked is an abomination; how much more, when he brings it with a wicked mind!",
    28: "A false witness will perish, but the man who listens to the truth will speak and endure.",
    29: "A wicked man hardens his face, but as for the upright, he establishes his ways.",
    30: "There is no wisdom nor understanding nor counsel against Yahweh.",
    31: "The horse is prepared for the day of battle; but victory is from Yahweh.",
}

WEB[22] = {
    1:  "A good name is more desirable than great riches, and loving favor is better than silver and gold.",
    2:  "The rich and the poor have this in common: Yahweh is the maker of them all.",
    3:  "A prudent man sees danger and hides himself, but the simple pass on and suffer for it.",
    4:  "The result of humility and the fear of Yahweh is wealth, honor, and life.",
    5:  "Thorns and snares are in the path of the crooked. Whoever guards his soul will stay far from them.",
    6:  "Train up a child in the way he should go, and when he is old he will not depart from it.",
    7:  "The rich rule over the poor, and the borrower is servant to the lender.",
    8:  "He who sows iniquity will reap trouble, and the rod of his fury will fail.",
    9:  "A generous man will be blessed, for he shares his food with the poor.",
    10: "Drive away a scoffer, and strife will go out; yes, quarrels and insults will stop.",
    11: "He who loves purity of heart and whose speech is gracious, the king will be his friend.",
    12: "The eyes of Yahweh watch over knowledge, but he frustrates the words of the unfaithful.",
    13: "The sluggard says, 'There is a lion outside! I will be killed in the streets!'",
    14: "The mouth of an adulteress is a deep pit; he who is under Yahweh's wrath will fall into it.",
    15: "Folly is bound up in the heart of a child; the rod of discipline drives it far away.",
    16: "Whoever oppresses the poor for his own increase and whoever gives to the rich, both lead to poverty.",
    # "Words of the Wise" preamble (22:17-21)
    17: "Turn your ear, and listen to the words of the wise. Apply your heart to my teaching.",
    18: "For it is a pleasant thing if you keep them within you, if they are all ready on your lips.",
    19: "That your trust may be in Yahweh, I teach you today, even you.",
    20: "Haven't I written to you thirty sayings of counsel and knowledge,",
    21: "to teach you true and reliable words, that you may give sound answers to those who sent you?",
    # Saying 1
    22: "Don't exploit the poor, because he is poor; and don't crush the needy in court;",
    23: "for Yahweh will plead their case, and plunder the life of those who plunder them.",
    # Saying 2
    24: "Don't befriend an angry man, and don't associate with a wrathful man,",
    25: "lest you learn his ways, and ensnare your soul.",
    # Saying 3
    26: "Don't you be one of those who strike hands, of those who are collateral for debts.",
    27: "If you don't have means to pay, why should he take your bed from under you?",
    # Saying 4
    28: "Don't move the ancient boundary stone, which your fathers have set up.",
    # Saying 5
    29: "Do you see a man skilled in his work? He will serve kings. He won't serve obscure men.",
}

WEB[23] = {
    1:  "When you sit down to eat with a ruler, consider carefully what is before you;",
    2:  "put a knife to your throat if you are a man given to appetite.",
    3:  "Don't be desirous of his delicacies, since they are deceptive food.",
    4:  "Don't weary yourself to be rich. In your wisdom, show restraint.",
    5:  "Why do you set your eyes on that which is not? For it certainly sprouts wings like an eagle and flies in the sky.",
    6:  "Don't eat the food of a stingy man, and don't desire his delicacies;",
    7:  "for as he thinks in his heart, so is he. 'Eat and drink,' he says to you, but his heart is not with you.",
    8:  "The morsel which you have eaten you will vomit up, and lose your pleasant words.",
    9:  "Don't speak in the hearing of a fool, for he will despise the wisdom of your words.",
    10: "Don't move the ancient boundary stone. Don't encroach on the fields of the fatherless;",
    11: "for their Defender is strong. He will plead their case against you.",
    12: "Apply your heart to instruction, and your ears to the words of knowledge.",
    13: "Don't withhold correction from a child. If you punish him with the rod, he will not die.",
    14: "Punish him with the rod, and save his soul from Sheol.",
    15: "My son, if your heart is wise, then my heart will be glad, even mine;",
    16: "yes, my heart will rejoice when your lips speak what is right.",
    17: "Don't let your heart envy sinners; but rather fear Yahweh all day long.",
    18: "Indeed surely there is a future hope for you, and your hope will not be cut off.",
    19: "Listen, my son, and be wise, and keep your heart on the right path.",
    20: "Don't be among wine drinkers, among gluttonous eaters of meat;",
    21: "for the drunkard and the glutton shall come to poverty, and drowsiness clothes them in rags.",
    22: "Listen to your father who gave you life, and don't despise your mother when she is old.",
    23: "Buy the truth, and don't sell it. Get wisdom, discipline, and understanding.",
    24: "The father of the righteous has great joy. Whoever fathers a wise child delights in him.",
    25: "Let your father and your mother be glad. Let her who bore you rejoice.",
    26: "My son, give me your heart; and let your eyes keep in my ways.",
    27: "For a prostitute is a deep pit; and a wayward wife is a narrow well.",
    28: "Yes, she lies in wait like a robber, and increases the unfaithful among men.",
    29: "Who has woe? Who has sorrow? Who has strife? Who has complaints? Who has needless bruises? Who has bloodshot eyes?",
    30: "Those who linger over wine, who go to taste mixed wine.",
    31: "Don't look at the wine when it is red, when it sparkles in the cup, when it goes down smoothly.",
    32: "In the end, it bites like a snake, and poisons like a viper.",
    33: "Your eyes will see strange things, and your mind will imagine confusing things.",
    34: "Yes, you will be as he who lies down in the middle of the sea, or as he who lies on top of the rigging.",
    35: "'They hit me and I was not hurt. They beat me and I didn't feel it. When will I wake up? I can do it again. I will look for more.'",
}

WEB[24] = {
    1:  "Don't be envious of evil men; neither desire to be with them;",
    2:  "for their hearts plot violence, and their lips talk about mischief.",
    3:  "Through wisdom a house is built; by understanding it is established;",
    4:  "by knowledge its rooms are filled with all rare and beautiful treasure.",
    5:  "A wise man has great power; and a knowledgeable man increases strength.",
    6:  "For by wise guidance you wage your war; and victory is in many advisors.",
    7:  "Wisdom is too high for a fool; he doesn't open his mouth in the gate.",
    8:  "One who plots to do evil will be called a schemer.",
    9:  "The schemes of folly are sin. The scoffer is an abomination to men.",
    10: "If you falter in the time of trouble, your strength is small.",
    11: "Rescue those who are being led away to death! Indeed, hold back those who are staggering to the slaughter!",
    12: "If you say, 'Behold, we didn't know this'; doesn't he who weighs the hearts consider it? He who keeps your soul, doesn't he know it? Shall he not render to every man according to his work?",
    13: "My son, eat honey, for it is good; the drippings of the honeycomb are sweet to your taste.",
    14: "Know that wisdom is the same for your soul; if you find it, then there will be a future, and your hope will not be cut off.",
    15: "Don't lie in wait, wicked man, against the home of the righteous; don't plunder his resting place.",
    16: "For a righteous man falls seven times, and rises up again; but the wicked are overthrown by calamity.",
    17: "Don't rejoice when your enemy falls. Don't let your heart be glad when he is overthrown;",
    18: "lest Yahweh see it, and it displease him, and he turn away his wrath from him.",
    19: "Don't fret yourself because of evildoers; neither be envious of the wicked;",
    20: "for there will be no future for the evil man. The lamp of the wicked shall be snuffed out.",
    21: "My son, fear Yahweh and the king. Don't associate with those who are given to change;",
    22: "for their calamity will rise suddenly; and the destruction from them both — who knows it?",
    23: "These also are sayings of the wise. To show partiality in judgment is not good.",
    24: "He who says to the wicked, 'You are righteous,' peoples shall curse him, and nations shall abhor him;",
    25: "but it will go well for those who convict the guilty, and a rich blessing will come on them.",
    26: "An honest answer is like a kiss on the lips.",
    27: "Prepare your work outside, and get your fields ready. Afterwards, build your house.",
    28: "Don't be a witness against your neighbor without cause. Don't deceive with your lips.",
    29: "Don't say, 'I will do to him as he has done to me; I will pay back the man according to his work.'",
    30: "I went by the field of the sluggard, by the vineyard of the man void of understanding;",
    31: "and behold, it was all grown over with thorns. Its surface was covered with nettles, and its stone wall was broken down.",
    32: "Then I saw, and considered well. I saw, and received instruction.",
    33: "'A little sleep, a little slumber, a little folding of the hands to sleep:'",
    34: "so your poverty will come as a robber, and your want as an armed man.",
}

WEB[25] = {
    1:  "These also are proverbs of Solomon, which the men of Hezekiah king of Judah copied out.",
    2:  "It is the glory of God to conceal a matter, but the glory of kings is to search out a matter.",
    3:  "As the heavens for height, and the earth for depth, so the hearts of kings are unsearchable.",
    4:  "Take away the dross from the silver, and material comes out for the smith;",
    5:  "take away the wicked from before the king, and his throne shall be established in righteousness.",
    6:  "Don't exalt yourself in the presence of the king, or stand in the place of great men;",
    7:  "for it is better that it be said to you, 'Come up here,' than that you should be put lower in the presence of the prince, whom your eyes have seen.",
    8:  "Don't be hasty in bringing charges to court. What will you do in the end when your neighbor puts you to shame?",
    9:  "Argue your case with your neighbor, and don't betray the confidence of another;",
    10: "lest one who hears it put you to shame, and your bad reputation never depart.",
    11: "A word fitly spoken is like apples of gold in settings of silver.",
    12: "As an earring of gold, and an ornament of fine gold, so is a wise reprover to an obedient ear.",
    13: "As the cold of snow in the time of harvest, so is a faithful messenger to those who send him; for he refreshes the soul of his masters.",
    14: "As clouds and wind without rain, so is he who boasts of gifts not given.",
    15: "By patience a ruler is persuaded. A soft tongue breaks the bone.",
    16: "Have you found honey? Eat as much as is sufficient for you, lest you eat too much, and vomit it.",
    17: "Let your foot be seldom in your neighbor's house, lest he be weary of you, and hate you.",
    18: "A man who gives false testimony against his neighbor is like a war club, a sword, or a sharp arrow.",
    19: "Confidence in an unfaithful man in time of trouble is like a bad tooth, or a lame foot.",
    20: "As one who takes away a garment in cold weather, or vinegar on soda, so is one who sings songs to a heavy heart.",
    21: "If your enemy is hungry, give him food to eat. If he is thirsty, give him water to drink;",
    22: "for you will heap coals of fire on his head, and Yahweh will reward you.",
    23: "The north wind brings forth rain; so does a backbiting tongue an angry face.",
    24: "It is better to dwell in the corner of a housetop than to share a house with a contentious woman.",
    25: "Like cold water to a weary soul, so is good news from a far country.",
    26: "Like a muddied spring, or a polluted well, so is a righteous man who gives way before the wicked.",
    27: "It is not good to eat much honey; so for men to search out their own glory is not glory.",
    28: "Like a city that is broken down and without walls is a man whose spirit is without restraint.",
}

WEB[26] = {
    1:  "Like snow in summer, and as rain in harvest, so honor is not fitting for a fool.",
    2:  "Like a fluttering sparrow, like a darting swallow, so an undeserved curse doesn't come to rest.",
    3:  "A whip is for the horse, a bridle for the donkey, and a rod for the back of fools!",
    4:  "Don't answer a fool according to his folly, lest you also be like him.",
    5:  "Answer a fool according to his folly, lest he be wise in his own eyes.",
    6:  "One who sends a message by the hand of a fool is cutting off feet and drinking violence.",
    7:  "Like the legs of the lame that hang loose, so is a parable in the mouth of fools.",
    8:  "As one who binds a stone in a sling, so is he who gives honor to a fool.",
    9:  "Like a thornbush that goes into the hand of a drunkard, so is a parable in the mouth of fools.",
    10: "As an archer who wounds all, so is he who hires a fool or who hires those who pass by.",
    11: "As a dog that returns to his vomit, so is a fool who repeats his folly.",
    12: "Do you see a man wise in his own eyes? There is more hope for a fool than for him.",
    13: "The sluggard says, 'There is a lion in the road! A fierce lion roams the streets!'",
    14: "As the door turns on its hinges, so does the sluggard on his bed.",
    15: "The sluggard buries his hand in the dish. He is too lazy to bring it back to his mouth.",
    16: "The sluggard is wiser in his own eyes than seven men who answer with discretion.",
    17: "Like one who grabs a dog's ears is one who passes by and meddles in a quarrel not his own.",
    18: "Like a madman who shoots firebrands, arrows, and death,",
    19: "so is the man who deceives his neighbor and says, 'Am I not joking?'",
    20: "For lack of wood, a fire goes out. Without gossip, a quarrel dies down.",
    21: "As coals are to hot embers, and wood to fire, so is a contentious man to kindling strife.",
    22: "The words of a gossip are like dainty morsels: they go down into a person's innermost parts.",
    23: "Like silver dross on an earthen vessel are the lips of a fervent one with an evil heart.",
    24: "A malicious man disguises himself with his lips, but he harbors evil in his heart.",
    25: "When his speech is charming, don't believe him; for there are seven abominations in his heart.",
    26: "His malice may be concealed by deception, but his wickedness will be exposed in the assembly.",
    27: "Whoever digs a pit shall fall into it. Whoever rolls a stone, it will come back on him.",
    28: "A lying tongue hates those it hurts; and a flattering mouth works ruin.",
}

WEB[27] = {
    1:  "Don't boast about tomorrow; for you don't know what a day may bring.",
    2:  "Let another man praise you, and not your own mouth; a stranger, and not your own lips.",
    3:  "A stone is heavy, and sand is a burden; but a fool's provocation is heavier than both.",
    4:  "Wrath is cruel, and anger is overwhelming; but who is able to stand before jealousy?",
    5:  "Better is open rebuke than hidden love.",
    6:  "Faithful are the wounds of a friend; although the kisses of an enemy are profuse.",
    7:  "A full soul loathes a honeycomb; but to a hungry soul, every bitter thing is sweet.",
    8:  "As a bird that wanders from her nest, so is a man who wanders from his home.",
    9:  "Perfume and incense bring joy to the heart; so does earnest counsel from a man's friend.",
    10: "Don't forsake your friend and your father's friend. Don't go to your brother's house in the day of your calamity; better is a neighbor who is near than a brother who is far away.",
    11: "My son, be wise, and bring joy to my heart, that I may answer one who taunts me.",
    12: "A prudent man sees danger and takes refuge; but the simple pass on, and suffer for it.",
    13: "Take his garment when he puts up collateral for a stranger. Hold it as a pledge when he does it for a wayward woman.",
    14: "He who blesses his neighbor with a loud voice early in the morning, it will be counted as a curse to him.",
    15: "A continual dripping on a rainy day and a contentious wife are alike;",
    16: "restraining her is like restraining the wind, or like holding oil in his right hand.",
    17: "Iron sharpens iron; so a man sharpens his friend's countenance.",
    18: "Whoever tends the fig tree shall eat its fruit. He who looks after his master shall be honored.",
    19: "As water reflects a face, so a man's heart reflects the man.",
    20: "Sheol and Abaddon are never satisfied; and a man's eyes are never satisfied.",
    21: "The crucible is for silver, and the furnace for gold; and a man is judged by his praise.",
    22: "Though you grind a fool in a mortar with a pestle along with grain, yet his folly will not be removed from him.",
    23: "Know the state of your flocks, and pay attention to your herds;",
    24: "for riches are not forever; nor does the crown endure to all generations.",
    25: "The hay is removed, and the new growth appears, the grasses of the hills are gathered in.",
    26: "The lambs are for your clothing, and the goats are the price of a field.",
    27: "There will be plenty of goats' milk for your food, for your household's food, and for the nourishment of your servant girls.",
}

WEB[28] = {
    1:  "The wicked flee when no one pursues; but the righteous are as bold as a lion.",
    2:  "In rebellion, a land has many rulers, but order is maintained by a man of understanding and knowledge.",
    3:  "A needy man who oppresses the poor is like a driving rain which leaves no crops.",
    4:  "Those who forsake the law praise the wicked; but those who keep the law contend with them.",
    5:  "Evil men don't understand justice; but those who seek Yahweh understand it fully.",
    6:  "Better is the poor who walks in his integrity, than he who is rich and crooked in his ways.",
    7:  "Whoever keeps the law is a wise son; but he who is a companion of gluttons shames his father.",
    8:  "He who increases his wealth by excessive interest gathers it for one who has pity on the poor.",
    9:  "He who turns away his ear from hearing the law, even his prayer is an abomination.",
    10: "Whoever causes the upright to go astray in an evil way, he will fall into his own trap; but the blameless will inherit good.",
    11: "The rich man is wise in his own eyes; but the poor who has understanding sees through him.",
    12: "When the righteous triumph, there is great glory; but when the wicked rise, men hide themselves.",
    13: "He who conceals his sins doesn't prosper, but whoever confesses and renounces them finds mercy.",
    14: "Blessed is the man who always fears; but one who hardens his heart falls into trouble.",
    15: "As a roaring lion or a charging bear, so is a wicked ruler over helpless people.",
    16: "A tyrannical ruler lacks judgment. One who hates ill-gotten gain will have long days.",
    17: "A man who is tormented by life blood will be a fugitive until death; no one will support him.",
    18: "Whoever walks blamelessly is kept safe; but one with perverse ways will fall suddenly.",
    19: "One who works his land will have an abundance of food; but one who chases fantasies will have his fill of poverty.",
    20: "A faithful man is rich with blessings; but one who is eager to be rich will not go unpunished.",
    21: "To show partiality is not good; yet a man will do wrong for a piece of bread.",
    22: "A stingy man hurries after riches, and doesn't know that poverty waits for him.",
    23: "One who rebukes a man will afterward find more favor than one who flatters with the tongue.",
    24: "Whoever robs his father or his mother, and says, 'It's not wrong,' is a partner with a destroyer.",
    25: "A greedy man stirs up strife; but one who trusts in Yahweh will prosper.",
    26: "One who trusts in himself is a fool; but one who walks in wisdom is kept safe.",
    27: "One who gives to the poor has no lack; but one who ignores them will have many curses.",
    28: "When the wicked rise, men hide themselves; but when they perish, the righteous thrive.",
}

WEB[29] = {
    1:  "He who is often rebuked and stiffens his neck will be destroyed suddenly, with no remedy.",
    2:  "When the righteous thrive, the people rejoice; but when the wicked rule, the people groan.",
    3:  "Whoever loves wisdom brings joy to his father; but a companion of prostitutes squanders his wealth.",
    4:  "The king by justice establishes the land; but he who takes bribes tears it down.",
    5:  "A man who flatters his neighbor spreads a net for his feet.",
    6:  "An evil man is snared by his sin, but the righteous can sing and be glad.",
    7:  "The righteous care about justice for the poor. The wicked aren't concerned about knowledge.",
    8:  "Mockers stir up a city, but the wise turn away wrath.",
    9:  "If a wise man goes to court with a foolish man, the fool rages or scoffs, and there is no peace.",
    10: "The bloodthirsty hate a man of integrity; and they seek the life of the upright.",
    11: "A fool vents all of his anger, but a wise man brings himself under control.",
    12: "If a ruler listens to false information, all of his officials will be wicked.",
    13: "The poor man and the oppressor have this in common: Yahweh gives sight to the eyes of both.",
    14: "The king who faithfully judges the poor, his throne shall be established forever.",
    15: "The rod of correction gives wisdom, but a child left to himself causes shame to his mother.",
    16: "When the wicked increase, sin increases; but the righteous will see their downfall.",
    17: "Correct your son, and he will give you rest. Yes, he will give delight to your soul.",
    18: "Where there is no revelation, the people cast off restraint; but one who keeps the law is blessed.",
    19: "A servant can't be corrected by words alone. Though he understands, yet he will not respond.",
    20: "Do you see a man who is hasty in his words? There is more hope for a fool than for him.",
    21: "One who pampers his servant from childhood will have him become a son in the end.",
    22: "An angry man stirs up strife, and a hot-tempered man commits many sins.",
    23: "A man's pride brings him low, but one of humble spirit gains honor.",
    24: "Whoever is an accomplice of a thief is an enemy of his own soul. He takes an oath, but dares not testify.",
    25: "The fear of man proves to be a snare, but whoever puts his trust in Yahweh is kept safe.",
    26: "Many seek the ruler's favor; but a man's justice comes from Yahweh.",
    27: "A dishonest man is detestable to the righteous; and one who is upright in the way is detestable to the wicked.",
}

# ─────────────────────────────────────────────────────────────────────────────
# Build the English JSON mirroring proverbs_fr.json structure exactly
# ─────────────────────────────────────────────────────────────────────────────

SUGGESTIONS_EN = {
    # Chapter 22 new units
    (22, (17, 18, 19, 20, 21)): ["Wisdom", "Instruction"],
    (22, (22, 23)): ["Justice", "Poverty"],
    (22, (24, 25)): ["Anger", "Friendship"],
    (22, (26, 27)): ["Prudence", "Wealth"],
    (22, (28,)): ["Justice", "Honesty"],
    (22, (29,)): ["Work", "Excellence"],
    # Chapter 23
    (23, (1, 2, 3)): ["Power", "Desire", "Prudence"],
    (23, (4, 5)): ["Wealth", "Work"],
    (23, (6, 7, 8)): ["Generosity", "Deception"],
    (23, (9,)): ["Wisdom", "Speech"],
    (23, (10, 11)): ["Justice", "Protection"],
    (23, (12,)): ["Wisdom", "Instruction"],
    (23, (13, 14)): ["Family", "Discipline"],
    (23, (15, 16)): ["Family", "Wisdom"],
    (23, (17, 18)): ["Hope", "Fear of God"],
    (23, (19, 20, 21)): ["Sobriety", "Poverty"],
    (23, (22, 23, 24, 25)): ["Family", "Wisdom", "Truth"],
    (23, (26, 27, 28)): ["Faithfulness", "Temptation"],
    (23, (29, 30, 31, 32, 33, 34, 35)): ["Sobriety", "Trap"],
    # Chapter 24
    (24, (1, 2)): ["Justice", "Envy"],
    (24, (3, 4)): ["Wisdom", "Family"],
    (24, (5, 6)): ["Wisdom", "Counsel"],
    (24, (7,)): ["Wisdom", "Folly"],
    (24, (8, 9)): ["Sin", "Folly"],
    (24, (10,)): ["Strength", "Courage"],
    (24, (11, 12)): ["Justice", "Responsibility"],
    (24, (13, 14)): ["Wisdom", "Hope"],
    (24, (15, 16)): ["Justice", "Perseverance"],
    (24, (17, 18)): ["Mercy", "Humility"],
    (24, (19, 20)): ["Justice", "Hope"],
    (24, (21, 22)): ["Authority", "Fear of God"],
    (24, (23, 24, 25)): ["Justice", "Judgment"],
    (24, (26,)): ["Truth", "Speech"],
    (24, (27,)): ["Work", "Wisdom"],
    (24, (28, 29)): ["Truth", "Revenge"],
    (24, (30, 31, 32, 33, 34)): ["Work", "Laziness"],
    # Chapters 25-29 merged units
    (25, (6, 7)): ["Humility", "Honor"],
    (25, (8, 9, 10)): ["Prudence", "Conflict"],
    (25, (21, 22)): ["Enemies", "Generosity"],
    (26, (20, 21, 22)): ["Conflict", "Gossip"],
    (26, (23, 24, 25, 26)): ["Deception", "Hypocrisy"],
    (27, (15, 16)): ["Family", "Conflict"],
    (27, (23, 24, 25, 26, 27)): ["Work", "Faithfulness"],
}

def make_reference_en(chapter, verses):
    if len(verses) == 1:
        return f"Proverbs {chapter}:{verses[0]}"
    return f"Proverbs {chapter}:{verses[0]}-{verses[-1]}"

def make_text(verse_dict, verses):
    if len(verses) == 1:
        return verse_dict[verses[0]]
    return " ".join(f"{v} {verse_dict[v]}" for v in verses if v in verse_dict)

def main():
    with open("src/data/proverbs_fr.json", "r", encoding="utf-8") as f:
        fr_data = json.load(f)

    en_data = []

    for item in fr_data:
        ch = item["chapter"]
        verses = item["verses"]
        ch_text = WEB.get(ch, {})

        if not ch_text:
            print(f"WARNING: no English text for chapter {ch}")
            continue

        text = make_text(ch_text, verses)
        if not text:
            print(f"WARNING: missing verse text for {ch}:{verses}")
            continue

        ref = make_reference_en(ch, verses)

        # Get English suggestions
        sugg_key = (ch, tuple(verses))
        suggestions = SUGGESTIONS_EN.get(sugg_key)
        if suggestions is None:
            # For single-verse units in chapters 10-22:16, translate the French suggestions
            fr_sugg = item.get("suggestions", [])
            sugg_map = {
                "Sagesse": "Wisdom", "Justice": "Justice", "Famille": "Family",
                "Colère": "Anger", "Richesse": "Wealth", "Travail": "Work",
                "Parole": "Speech", "Dieu": "God", "Pauvreté": "Poverty",
                "Honnêteté": "Honesty", "Instruction": "Instruction",
                "Humilité": "Humility", "Amitié": "Friendship",
                "Discipline": "Discipline", "Espérance": "Hope",
                "Fidélité": "Faithfulness", "Prudence": "Prudence",
                "Orgueil": "Pride", "Péché": "Sin", "Folie": "Folly",
                "Force": "Strength", "Miséricorde": "Mercy", "Mensonge": "Lying",
                "Protection": "Protection", "Générosité": "Generosity",
                "Excellence": "Excellence", "Tromperie": "Deception",
                "Sobriété": "Sobriety", "Vengeance": "Revenge",
                "Paresse": "Laziness", "Jugement": "Judgment",
                "Conseil": "Counsel", "Courage": "Courage",
                "Vérité": "Truth", "Piège": "Trap", "Envie": "Envy",
                "Réputation": "Reputation", "Autorité": "Authority",
                "Crainte de Dieu": "Fear of God", "Responsabilité": "Responsibility",
                "Persévérance": "Perseverance", "Pouvoir": "Power",
                "Convoitise": "Desire", "Tentation": "Temptation",
            }
            suggestions = [sugg_map.get(s, s) for s in fr_sugg]

        en_data.append({
            "id":          item["id"],
            "chapter":     ch,
            "verses":      verses,
            "text":        text,
            "reference":   ref,
            "suggestions": suggestions,
        })

    out_path = "src/data/proverbs_en.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(en_data, f, ensure_ascii=False, indent=2)

    print(f"Written {len(en_data)} units to {out_path}")
    single = sum(1 for p in en_data if len(p["verses"]) == 1)
    multi  = sum(1 for p in en_data if len(p["verses"]) > 1)
    print(f"Single-verse: {single}, Multi-verse: {multi}")

if __name__ == "__main__":
    main()
